config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'comments/new'
  get 'comments/create'
  get 'likes/like'
  root to: 'users#index'
  get "/users/:user_id/posts", to: "posts#index", as: "user_posts"
  post "/users/:user_id/posts", to: "posts#create", as: "user_create_post"
  get "/users/:user_id/posts/new", to: "posts#new", as: "user_new_post"
  get "/users/:user_id/posts/:id", to: "posts#show", as: "user_post"
  post "/users/:user_id/posts/:id", to: "comments#create", as: "user_create_post_comment"
  get "/users/:user_id/posts/:id/new", to: "comments#new", as: "user_new_post_comment"
  post "/users/:user_id/posts/:id/like", to: "likes#like", as: "user_create_post_like"
  get "/users", to: "users#index", as: "users"
  get "/users/:id", to: "users#show", as: "user"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post
    can :create, Comment
    can :manage, Post, author_id: user.id
    can :manage, Comment, author_id: user.id
    return unless user.admin?
  end

  # See the wiki for details:
  # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  def self.update_comments_counter(post)
    counter = Comment.where("post_id = #{post.id}").count
    post.comments_counter = counter
    post.save
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  def self.update_likes_counter(post)
    counter = Like.where("post_id = #{post.id}").count
    post.likes_counter = counter
    post.save
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.update_post_counter(user)
    counter = Post.where("author_id = #{user.id}").count
    user.posts_counter = counter
    user.save
  end

  def self.most_recent_comments(post)
    Comment.where("post_id = #{post.id}").order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id', class_name: 'Post', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', class_name: 'Comment', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', class_name: 'Like', dependent: :destroy
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.most_recent_posts(user)
    Post.joins(:author).where(users: { id: user.id }).order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :bio, :photo, :posts_counter, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :photo, :posts_counter, :email,
               :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new
    @comment.text = params[:comment][:text]
    @comment.author_id = current_user.id
    @comment.post_id = params[:id]
    if @comment.save
      flash[:notice] = 'Success'
      redirect_to user_post_url(id: params[:id], user_id: params[:user_id])
    else
      flash[:notice] = 'Error'
      render :new
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def like
    @like = Like.new
    @like.author_id = current_user.id
    @like.post_id = params[:id]
    if @like.save
      redirect_to user_post_url(id: params[:id], user_id: params[:user_id])
    else
      flash.now[:error] = 'Error'
      redirect_to user_posts_url(user_id: params[:user_id])
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :update_interactions

  def index
    @user = User.find(params[:user_id])
    @userlist = User.all
    @posts = Post.joins(:author).where(users: { id: @user.id }).order(created_at: :desc)
    @comments = Comment.includes(:author).order(created_at: :desc)
  end

  def show
    @user = User.find(params[:user_id])
    @userlist = User.all
    @post = Post.find(params[:id])
    @comments = Comment.includes(:author).order(created_at: :desc)
    @posts = Post.joins(:author).where(users: { id: @user.id }).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new
    @post.title = params[:post][:title]
    @post.text = params[:post][:text]
    @post.author_id = params[:user_id]
    @post.comments_counter = 0
    @post.likes_counter = 0
    if @post.save
      flash[:notice] = 'Success'
      redirect_to user_posts_url(@post.author_id)
    else
      flash.now[:error] = 'Error'
      render :new
    end
  end

  private

  def update_interactions
    @posts = Post.all
    @posts.each do |post|
      Comment.update_comments_counter(post)
      Like.update_likes_counter(post)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :update_interactions

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = User.most_recent_posts(@user)
  end

  private

  def update_interactions
    @users = User.all
    @users.each do |user|
      Post.update_post_counter(user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="add_comment_main_container">
<% flash.each do |type, msg| %>
    <% if type == 'notice' %>
      <div class="flash-notice">
        <%= msg %>
      </div>
    <% end %>
    <% if type == 'error' %>
      <div class="flash-error">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <%= form_with model: @comment, url: user_create_post_comment_path, method: :post, class: 'add_comment_form' do |form| %>
    <h1 class='add_comment_head_title'>Add Comment </h1>
    <%= form.label :text, "Comment:", class: 'add_comment_form_label' %>
    <%= form.text_field :text, :required => true, class: 'add_comment_form_input' %>
    <%= form.submit "Add comment", class: 'add_comment_form_btn' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class='post_index_main_wrapper'>
  <% flash.each do |type, msg| %>
    <% if type == 'notice' %>
      <div class="flash-notice">
        <%= msg %>
      </div>
    <% end %>
    <% if type == 'error' %>
      <div class="flash-error">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <div class='post_index_user_detail_wraper'>
    <div class='post_index_user_img'>photo</div>
    <div class='post_index_user_info_area'>
      <h1 class='post_index_user_name_tag'><%= @user.name %></h2>
      <h2 class='post_index_user_posts_count'>Number of posts: <%= @user.posts_counter %></h4>
    </div>
  </div>
  <ul class='post_index_posts_container'>
    <% @posts.each do |post| %>
      <li class='post_index_post_li'>
        <div class='post_index_header_area'>
            <h1 class='post_index_post_title'><%= link_to post.title, user_post_path(user_id: @user, id: post.id), class: 'post_index_title_link' %></h1>
            <p class='post_index_post_text'><%= post.text %></p>
            <h2 class='post_index_comments_and_likes_counter'>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></h2>
        </div>
        <ul class='post_index_comments_list'>
          <% @comments.each do |comment| %>
            <% if comment.post_id == post.id %>
              <li class='post_index_comments_text'>
                <%= @userlist.find(comment.author_id).name %>: <%= comment.text %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
  <div class='user_show_user_button'>
    <%= link_to "Pagination", user_posts_path(user_id: @user), class: 'post_index_pag_btn' %>
  </div>
</div>

app/views/posts/new.html.erb
<section class="post_new_main_container">
  <% flash.each do |type, msg| %>
    <% if type == 'notice' %>
      <div class="flash-notice">
        <%= msg %>
      </div>
    <% end %>
    <% if type == 'error' %>
      <div class="flash-error">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <%= form_with model: @post, url: user_create_post_path, method: :post, class: 'post_new_form' do |form| %>
    <h2 class="post_new_add_post_indicator">Add Post: </h2>
      <%= form.label :title, class: 'post_new_title_label' %>
      <%= form.text_field :title, :required => true, class: 'post_new_title_input' %>
      <%= form.label :text, class: 'post_new_text_label' %>
      <%= form.text_field :text, :required => true, class: 'post_new_text_input' %>
      <%= form.submit "Add post", class: 'post_new_submit_btn' %>
  <% end %>
</section>

app/views/posts/show.html.erb
<div class='post_show_main_wrapper'>
  <% flash.each do |type, msg| %>
    <% if type == 'notice' %>
      <div class="flash-notice">
        <%= msg %>
      </div>
    <% end %>
    <% if type == 'error' %>
      <div class="flash-error">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <div class='post_show_post_wrapper'>
    <div class='post_show_post_content_wrapper'>
      <h1 class='post_show_post_title'><%= @post.title %> by: <%= @user.name %></h1>
      <h2 class='post_show_post_comment_counter'>Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></h2>
    </div>
    <p class='post_show_post_text'><%= @post.text %></p>
  </div>
    <ul class='post_show_post_comments_wrapper'>
        <% @comments.each do |comment| %>
            <% if comment.post_id == @post.id %>
            <li class='post_show_post_comment'>
                <%= @userlist.find(comment.author_id).name %>: <%= comment.text %>
            </li>
            <% end %>
        <% end %>
    </ul>
    <div class="post_show_btns">
      <%= button_to 'Like', user_create_post_like_path, method: :post, class: 'post_show_add_like_btn' %>
      <%= link_to 'Add Comment', user_new_post_comment_path(@user), class: 'post_show_add_comment_btn' %>
   </div>
</div>

app/views/users/index.html.erb
  <ul class='users_index_main_wrapper'>
    <% @users.each do |user| %>
      <li class='users_index_user_li'>
        <div class='users_index_user_photo'>photo</div>
        <div class='users_index_user_info'>
          <%= link_to user do %>
            <h1 class='users_index_user_name'><%= user.name %></h1>
            <h2 class='users_index_user_posts'>Number of posts: <%= user.posts_counter %></h2>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>

app/views/users/show.html.erb
<div class='user_show_main_wrapper'>
  <div class='user_show_user_info_wrapper'>
    <div class='user_show_user_photo'>photo</div>
    <div class='user_show_user_detail_wrapper'>
      <h2 class='user_show_user_name'><%= @user.name %></h2>
      <h4 class='user_show_user_post_counter'>Number of posts: <%= @user.posts_counter %></h4>
    </div>
  </div>
  <div class='user_show_user_bio_wrapper'>
    <h1 class='user_show_user_bio_tag'>Bio</h1>
    <p class='user_show_user_bio_detail'>
      <%= @user.bio %>
    </p>
  </div>
  <ul class='user_show_user_posts_wrapper'>
    <% @posts.each do |post| %>
      <li class='user_show_user_post'>
        <h1 class='user_show_user_post_title'><%= link_to post.title, user_post_path(user_id: @user, id: post.id) %></h1>
        <p class='user_show_user_post_text'><%= post.text %></p>
        <h2 class='user_show_user_post_comments'>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></h2>
      </li>
    <% end %>
  </ul>
  <div class='user_show_user_button'>
    <%= link_to "See all posts", user_posts_path(user_id: @user), class: 'user_show_see_all_post_link' %>
  </div>
</section>